# Configuration constants
NUM_UNIVERSITIES = 200
NUM_STUDENTS = 50000
MIN_PROGRAMS_PER_UNIVERSITY = 3
MAX_PROGRAMS_PER_UNIVERSITY = 5
HISTORICAL_RECORDS_PER_PROGRAM = 50
ALUMNI_RECORDS_PER_PROGRAM = 50
FUNDING_RECORDS_PER_UNIVERSITY = 5
RANKINGS_PER_PROGRAM = 3
PREDICTIONS_PER_STUDENT = 5
WISHLIST_ITEMS_PER_STUDENT = 10
APPLICATIONS_PER_STUDENT = 10

# Seed for reproducibility
SEED = 42