# Data Volume Configuration
NUM_UNIVERSITIES = 200
NUM_STUDENTS = 50000
MIN_PROGRAMS_PER_UNIVERSITY = 3
MAX_PROGRAMS_PER_UNIVERSITY = 5
HISTORICAL_RECORDS_PER_PROGRAM = 50
ALUMNI_RECORDS_PER_PROGRAM = 50
FUNDING_RECORDS_PER_UNIVERSITY = 5
RANKINGS_PER_PROGRAM = 3
PREDICTIONS_PER_STUDENT = 5
WISHLIST_ITEMS_PER_STUDENT = 10
APPLICATIONS_PER_STUDENT = 10

# Data Quality Configuration
DIRTY_DATA_PROBABILITY = 0.15
DUPLICATE_PROBABILITY = 0.05
MISSING_DATA_PROBABILITY = 0.1

# Date and Year Configuration
APPLICATION_YEAR = 2024
HISTORICAL_YEAR_RANGE = (2018, 2023)
GRADUATION_YEAR_RANGE = (2015, 2023)

# Student Configuration
MIN_STUDENT_AGE = 18
MAX_STUDENT_AGE = 35

# Seed for Reproducibility
SEED = 42